schema_version = "1.0.0"
id = "booltron"
version = "3.2.2"
name = "Booltron"
tagline = "Super add-on for superfast booleans"
maintainer = "Mikhail Rachinskiy"
type = "add-on"
tags = ["Modeling", "Object"]
blender_version_min = "4.2.0"
website = "https://github.com/mrachinskiy/booltron"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2014-2025 Mikhail Rachinskiy"]
